# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=255, verbose_name=b'Campaign Name')),
                ('goal', models.DecimalField(decimal_places=2, default=500, max_digits=8, verbose_name=b'Goal')),
                ('duration', models.IntegerField(default=b'7', verbose_name=b'Duration of the campaign')),
                ('ctype', models.CharField(choices=[(b'BEACON', b'BEACON')], max_length=6, verbose_name=b'Campagin Type')),
                ('status', models.CharField(choices=[(b'FAILED', b'FAILED'), (b'ACTIVE', b'ACTIVE')], default=b'ACTIVE', max_length=6, verbose_name=b'Campaign status')),
                ('next_campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_campaign', to='crowdao.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='beaconcampaign',
            name='duration',
            field=models.IntegerField(default=b'7', verbose_name=b'Duration of the campaign'),
        ),
        migrations.AddField(
            model_name='beaconcampaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8, verbose_name=b'Goal'),
        ),
        migrations.AddField(
            model_name='beaconcampaign',
            name='name',
            field=models.CharField(default=b'', max_length=255, verbose_name=b'Campaign Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='recurrent',
            field=models.BooleanField(default=False, verbose_name=b'Make this a recurrent donation'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'REIMBU', b'REIMBURSED'), (b'FINAL', b'FINALIZED'), (b'TRANSF', b'Transferred to follow-up campaign')], default=1, max_length=10, verbose_name=b'status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crowdao.Campaign'),
        ),
    ]
