# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdao', '0002_auto_20161004_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charge_id',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Stripe Charge id'),
        ),
    ]
